version: '3'
services:
  pappdoc:
    build: .
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    tty: true